services:
  db_postgres:
    image: postgres:16-alpine
    container_name: db_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_POSTGRES_DB:-postgres}
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    depends_on:
      - db_postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_postgres_data:
  pgadmin_data: